In [1]:
import numpy as np

In [ ]:
oneD = np.array([1,2,3])
twoD = np.array([[1,2,3],[4,5,6]])
threeD = np.array([[[1,2,3,4],[6,7,8,9]],[[4,5,6,7],[8,9,10,11]]])
fourD = np.array([[[[1,2,3,4],[6,7,8,9]],[[4,5,6,7],[8,9,10,11]]],[[[1,2,3,4],[6,7,8,9]],[[4,5,6,7],[8,9,10,11]]]])

[[[ 1  2  3  4]
  [ 6  7  8  9]]

 [[ 4  5  6  7]
  [ 8  9 10 11]]]
[[[[ 1  2  3  4]
   [ 6  7  8  9]]

  [[ 4  5  6  7]
   [ 8  9 10 11]]]


 [[[ 1  2  3  4]
   [ 6  7  8  9]]

  [[ 4  5  6  7]
   [ 8  9 10 11]]]]
