In [1]:
import numpy as np

In [ ]:
oneD = np.array([1,2,3])
twoD = np.array([[1,2,3],[4,5,6]])
threeD = np.array([[[1,2,3,4],[6,7,8,9]],[[4,5,6,7],[8,9,10,11]]])
fourD = np.array([[[[1,2,3,4],[6,7,8,9]],[[4,5,6,7],[8,9,10,11]]],[[[1,2,3,4],[6,7,8,9]],[[4,5,6,7],[8,9,10,11]]]])

[[[ 1  2  3  4]
  [ 6  7  8  9]]

 [[ 4  5  6  7]
  [ 8  9 10 11]]]
[[[[ 1  2  3  4]
   [ 6  7  8  9]]

  [[ 4  5  6  7]
   [ 8  9 10 11]]]


 [[[ 1  2  3  4]
   [ 6  7  8  9]]

  [[ 4  5  6  7]
   [ 8  9 10 11]]]]


In [6]:
import pandas as pd

mylist1 = [1,2,3,4,5,6,7,8,9,10]
mylist2 = [["Apple", "Orange"], ["Sauce", "Ketchup", "Jam"], ["James","Jessie"]]

myDataFrame = pd.DataFrame(mylist2, columns = ["A","B","C"], index = ["a","b","c"])
print(myDataFrame)

       A        B     C
a  Apple   Orange  None
b  Sauce  Ketchup   Jam
c  James   Jessie  None


In [6]:
import numpy as np
import pandas as pd

array1 = np.array([["Lionel Messi", "Cristiano Ronaldo", "Neymar Jr"], 
                  ["Zinedine Zidane", "Kevin De Bruyne", "Sergio Busquets"], 
                  ["Roberto Carlos", "Maldini", "Dani Alves"]])

playing9 = pd.DataFrame(array1, columns=["Left","Center","Right"], index=["Attack", "Midfield", "Defense"])

print(playing9)

                     Left             Center            Right
Attack       Lionel Messi  Cristiano Ronaldo        Neymar Jr
Midfield  Zinedine Zidane    Kevin De Bruyne  Sergio Busquets
Defense    Roberto Carlos            Maldini       Dani Alves
