In [1]:
import numpy as np

In [ ]:
oneD = np.array([1,2,3])
twoD = np.array([[1,2,3],[4,5,6]])
threeD = np.array([[[1,2,3,4],[6,7,8,9]],[[4,5,6,7],[8,9,10,11]]])
fourD = np.array([[[[1,2,3,4],[6,7,8,9]],[[4,5,6,7],[8,9,10,11]]],[[[1,2,3,4],[6,7,8,9]],[[4,5,6,7],[8,9,10,11]]]])

[[[ 1  2  3  4]
  [ 6  7  8  9]]

 [[ 4  5  6  7]
  [ 8  9 10 11]]]
[[[[ 1  2  3  4]
   [ 6  7  8  9]]

  [[ 4  5  6  7]
   [ 8  9 10 11]]]


 [[[ 1  2  3  4]
   [ 6  7  8  9]]

  [[ 4  5  6  7]
   [ 8  9 10 11]]]]


In [3]:
import pandas as pd

mylist1 = [1,2,3,4,5,6,7,8,9,10]
mylist2 = [["Apple", "Orange"], ["Sauce", "Ketchup"], ["James","Jessie"]]

myDataFrame = pd.DataFrame(mylist2)
print(myDataFrame)

       0        1
0  Apple   Orange
1  Sauce  Ketchup
2  James   Jessie
